### ISSUE TITLE
[Proposal] BitDevs: Bitcoin Socratic Seminar - multisigbackup.com

### ISSUE THREAD

**Issue by joshdoman** [ATLBitLab/calendar#47]
```meta
UTCTime: 2024-XX-XX 22:00 UTC (TBD)
Duration: 1h
Location: ATL BitLab, 684 John Wesley Dobbs Ave NE, Unit A1, Atlanta, GA 30312
```

<img width="1461" alt="Screenshot 2024-12-05 at 11 33 30 AM" src="https://github.com/user-attachments/assets/de5a81df-7926-46e2-aeb1-ae33c28ac07f">

## Details

This is a topic proposal for a future Bit Devs Socratic Seminar. I recently released an open source project, [multisigbackup.com](https://multisigbackup.com), which aims to simplify the process of backing up a 2-of-3 multisig descriptor, so that anyone, including a loved one, can always recover it with only 2 seeds.

### How it works
This tool strips all the sensitive data in a `k-of-n` descriptor (master fingerprints, xpubs) and encrypts it such that it can’t be decrypted without `k` xpubs. The tool then helps the user inscribe the data publicly on Bitcoin, including the descriptor template, derivation paths, and a hash of each pair of master fingerprints.

To recover, the user simply inputs two master fingerprints, which are hashed and used to find the encrypted descriptor onchain. An open source [indexer](https://github.com/joshdoman/multisig-recovery) makes this near instantaneous. Once the user has the encrypted descriptor, they use the derivation paths in the descriptor template to derive `k` xpubs, decrypt the encrypted data, and reassemble the original descriptor.

Ledger and Trezor hardware wallets are integrated into the recovery process for ease-of-use.

Source code: https://github.com/joshdoman/multisig-backup

### Agenda

- Intro to threshold multisigs and multisig descriptors
- Existing best practices for backing up descriptors
- Benefits and drawbacks of inscribing descriptors on Bitcoin
- High-level overview of the project
- Deep dive on shamir secret sharing and threshold encryption scheme
- Deep dive on recovery process
- Live demonstration
- Future development

### Location

**ATL BitLab**
684 John Wesley Dobbs Ave NE, Unit A1, Atlanta, GA 30312
📍 [Map Link](https://maps.app.goo.gl/zVuAWxasq9qsQmvg6)

Park in the gravel lot. Look for the orange door behind the fence.

**Comment by sbddesign** [comment]
Hey thanks for the topic @joshdoman. Do you think you could post it over here? https://github.com/atlantabitdevs/atlbit.dev/issues

**Comment by joshdoman** [comment]
Yes, my bad. I'll do that.
